"""Turn content/OL/src/Tn.txt into practice_Tn.gsm: each MCQ, its four options, then its answer in bold.

Source blocks, separated by blank lines:
    Q: stem
    A: option | option | option | option
    K: letter | one-line reason

Key letters are rebalanced so each topic's answers spread across A–D: an option set is
reordered only where that changes nothing a reader relies on — ordered numbers and dates stay
in order, and a closing "None of these"-type option stays last.
"""
import random
import re
import sys
from pathlib import Path

HERE = Path(__file__).parent
L = "ABCD"
FIXED = re.compile(r"none of these|all of these|both a and b", re.I)
NUMERIC = re.compile(r"^[\d~≈]|^about \d|^(one|two|three|four|five|six|seven|eight|nine|ten)\b|^(article|section|sdg) ", re.I)


def parse(path):
    out = []
    for blk in re.split(r"\n\s*\n", path.read_text().strip()):
        d = dict(ln.split(": ", 1) for ln in blk.strip().splitlines())
        opts = [o.strip() for o in d["A"].split("|")]
        key, why = (x.strip() for x in d["K"].split("|", 1))
        if len(opts) != 4 or key not in L:
            sys.exit(f"{path.name}: bad block → {d['Q'][:60]}")
        out.append(dict(q=d["Q"].strip(), opts=opts, key=L.index(key), why=why))
    return out


def slots(m):
    """Positions the correct option may be moved to."""
    o = m["opts"]
    if all(NUMERIC.match(x) for x in o):
        return []
    fixed = [i for i, x in enumerate(o) if FIXED.search(x)]
    if not fixed:
        return [0, 1, 2, 3]
    if fixed == [3] and m["key"] != 3:
        return [0, 1, 2]
    return []


def balance(items, seed):
    rng = random.Random(seed)
    count = [0] * 4
    for m in items:
        if not slots(m):
            count[m["key"]] += 1
    # the most constrained first, so the free ones can even out what they leave
    for m in sorted(items, key=lambda m: len(slots(m))):
        s = slots(m)
        if s:
            low = min(count[i] for i in s)
            target = rng.choice([i for i in s if count[i] == low])
            o = m["opts"]
            o[m["key"]], o[target] = o[target], o[m["key"]]
            m["key"] = target
            count[target] += 1
    return count


def main():
    for src in sorted((HERE / "src").glob("T*.txt")):
        t = int(src.stem[1:])
        items = parse(src)
        count = balance(items, 1000 + t)
        q = [f"%% generated by make_ol.py from src/{src.name}; edit the source, not this file", ""]
        for i, m in enumerate(items, 1):
            q.append(f"{i}. {m['q']}")
            q.append("(A) " + "  ".join(f"({L[j]}) {o}" if j else o for j, o in enumerate(m["opts"])))
            q.append(f"Ans: ^^Answer: ({L[m['key']]}) {m['opts'][m['key']]}^^ — {m['why']}")
            q.append("")
        (HERE / f"practice_T{t}.gsm").write_text("\n".join(q))
        print(f"T{t}: {len(items)} MCQs; keys A–D = {count}")


if __name__ == "__main__":
    main()
